name: Frontend deployment to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-to-gcp-frontend.yaml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
  IMAGE_NAME: ${{ secrets.FRONTEND_IMAGE_NAME }}
  SERVICE_NAME: ${{ secrets.FRONTEND_SERVICE_NAME }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
  IMAGE_TAG: ${{ github.sha }}
  FULL_IMAGE_PATH: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth-gcloud'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT_KEY }}'

      - name: Configure Docker 
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Tag Image
        run: |
          docker build -t ${{ env.FULL_IMAGE_PATH }} ./frontend
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Image to Artifact Registry
        run: |
          docker push ${{ env.FULL_IMAGE_PATH }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: ${{ env.FULL_IMAGE_PATH }}
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          allow_unauthenticated: true
